#!/usr/bin/env python3
from __future__ import annotations

import ast
import re

_HEADER_RE = re.compile(
    r"^(?:#.*TitanCrypt.*\n|#\s*Encrypted with.*\n|#\s*Generated by.*\n)+",
    re.IGNORECASE,
)
_TRAILING_SPACES = re.compile(r"[ \t]+\n")


def _looks_text(data: bytes) -> bool:
    if not data or b"\x00" in data[:8192]:
        return False
    sample = data[:8192]
    try:
        sample.decode("utf-8")
    except UnicodeDecodeError:
        return False
    printable = sum(32 <= b <= 126 or b in (9, 10, 13) for b in sample)
    return printable / max(len(sample), 1) > 0.85


def clean_source(data: bytes) -> bytes:
    if not _looks_text(data):
        return data
    text = data.decode("utf-8", errors="replace").replace("\r\n", "\n").replace("\r", "\n")
    if text.startswith("\ufeff"):
        text = text[1:]
    text = _HEADER_RE.sub("", text)
    text = _TRAILING_SPACES.sub("\n", text)
    text = text.strip("\n") + "\n"
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return text.encode("utf-8")
    try:
        pretty = ast.unparse(tree)
    except Exception:
        return text.encode("utf-8")
    if not pretty.endswith("\n"):
        pretty += "\n"
    return pretty.encode("utf-8")
